version: '1'
services:
  django:
    build:
      context: ./AlertHarvest
      dockerfile: Dockerfile
    image: alertharvest:latest
    ports:
      - 8000:8000
    volumes:
      - ./AlertHarvest:/app
    container_name: django-alertharvest
    depends_on:
      - redis
    networks:
      - AlertHarvest
  redis:
    image: "redis:latest"
    container_name: redis
    networks:
      - AlertHarvest

# Create the "monitoring" network if it doesn't exist
networks:
  AlertHarvest:
    name: AlertHarvest
    driver: bridge