# Generated by Django 5.0 on 2023-12-27 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('WARNING', 'Warning'), ('INFO', 'Info')], default='INFO', max_length=15)),
                ('message', models.TextField()),
                ('source', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed'), ('ACKNOWLEDGED', 'Acknowledged'), ('EXPIRED', 'Expired')], default='OPEN', max_length=15)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('last_occurrence', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
