# Generated by Django 5.0 on 2023-12-28 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='severity',
            field=models.CharField(choices=[('CRITICAL', 'Critical'), ('MAJOR', 'Major'), ('WARNING', 'Warning')], default='WARNING', max_length=15),
        ),
    ]
