# Generated by Django 5.0 on 2024-07-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
